# Added 11/8/17 to make MLfD class work easier
alias ml-venv='source ~/venvs_class/ml_class/bin/activate'
alias vision-venv='source ~/venvs_class/vision_class/bin/activate'
alias venv366='source ~/venvs_class/venv3.6.6/bin/activate'

# Added 11/27/17 to open pdf files without remembering xdg
alias open-pdf='xdg-open'

# Added 11/29/17 because I'm sick of typing it all out
alias juno='jupyter notebook'
alias deact='deactivate'

alias cuda-device-query='~/Packages/cuda/NVIDIA_CUDA-9.0_Samples/bin/x86_64/linux/release/deviceQuery'

alias ssh-pi='ssh pi@192.168.42.1'


alias algo-hw='evince ~/Documents/Books/Algorithm\ Design\ by\ Jon\ Kleinberg\,\ Eva\ Tardos.pdf'
#alias nautilus='nautilus --no-desktop'

alias wifi='nmcli c up'

alias hnsw-dir='cs /home/joshbeard/GitHub/nmslib/similarity_search/src/method'
alias algo-dir='cs /home/joshbeard/Dropbox/algo_cs-6210'
alias opsys-dir='cs /home/joshbeard/Dropbox/opsys_cs-6140'

alias zap24='nmcli c up Zap\ LANnigan\ \(2.4\ GHz\)'
alias zap5='nmcli c up Zap\ LANnigan\ \(5\ GHz\)'

# Run to get class of program (must click on it)
alias get-class='xprop | grep WM_CLASS'

# Run to turn on laptop screen
alias laptop-screen='xrandr --output eDP-1-1 --mode 1920x1080 --left-of HDMI-1-2'
alias laptop-screen-off='xrandr --output eDP-1-1 --off'
alias hdmi-off='xrandr --output HDMI-1-2 --off'
alias lab-screen='xrandr --output HDMI-1-2 --mode 1920x1200 --right-of eDP-1-1'
alias home-screen='xrandr --output HDMI-1-2 --mode 1920x1080 --right-of eDP-1-1'

#alias another='urxvt &' 

alias tasks='git -C ~/code/task pull; task next'
alias task-push='git -C ~/code/task commit -am "updates"; git -C ~/code/task push'
alias task-pull='git -C ~/code/task pull'

alias gcwip='git commit -am "wip"'

alias vimwiki='vim index.wiki'

alias ssh-submitty='ssh beardj2@submitty.cs.rpi.edu'
export SUBMITTY_PCR='/var/local/submitty/private_course_repositories/computational_vision'

alias package-wheel='python3 setup.py sdist bdist_wheel'
alias package-upload='twine upload dist/*'

alias tmux-attach='tmux attach -t'
alias tmux-new='tmux new -s'

alias ssh-port-forward='ssh -L 16006:127.0.0.1:6006'
